- name: Install Tomcat WebServer
  command:
    shell: "{{ item }}"
    chdir: /usr/local/bin
    loop:
      - "wget http://www.trieuvan.com/apache/tomcat/tomcat-7/{{tomcat_version}}/bin/apache-tomcat-7.0.90.tar.gz"
      - "tar xvzf apache-tomcat-7.0.90.tar.gz"
      - 'echo "PATH=/usr/local/bin/apache-tomcat-7.0.90/bin:$PATH" >> ~/.bashrc'
      - 'echo "PATH=/usr/local/bin/apache-tomcat-7.0.90/bin:$PATH" >> ~/.profile'
