- name: Install Tomcat WebServer
  command:
    shell: "{{ item }}"
    loop:
      - "wget http://www.trieuvan.com/apache/tomcat/tomcat-7/{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"
      - "tar xvzf apache-tomcat-{{tomcat_version}}.tar.gz"
      - "mv apache-tomcat-{{tomcat_version}} /home/{{user}}/apache-tomcat-{{tomcat_version}}"
      - 'echo "PATH=/home/{{user}}/apache-tomcat-{{tomcat_version}}/bin:$PATH" >> ~/.bashrc'
      - 'echo "PATH=/home/{{user}}/apache-tomcat-{{tomcat_version}}/bin:$PATH" >> ~/.profile'
